###
POST http://localhost:4003/payment
Content-Type: application/json
Authorization: Bearer token

{
 "paymentConfigKey": "STRIPE",
 "productId": "Product Id",
 "quantity": 1
}

###
POST http://localhost:4003/payment/init-with-external-transaction-id
Content-Type: application/json
Authorization: Bearer token

{
 "paymentConfigKey": "STRIPE",
 "external_transaction_id": "cs_test_transaction_id",
 "productId": "Product Id"
}
