### Create Payment
POST http://localhost:4003/payment
Content-Type: application/json
Authorization: Bearer token

{
 "payment_config_key": "STRIPE",
 "product_id": "Product Id",
 "quantity": 1
}

### Init Payment With External Transaction Id
POST http://localhost:4003/payment/init-with-external-transaction-id
Content-Type: application/json
Authorization: Bearer token

{
 "payment_config_key": "STRIPE",
 "external_transaction_id": "cs_test_transaction_id",
 "product_id": "Product Id"
}
