### Webhook
POST http://localhost:4003/webhook/coinbase?key=COINBASE
Content-Type: application/json

{
  "attempt_number": 1,
  "event": {
    "api_version": "2018-03-22",
    "created_at": "2020-06-01T19:43:19Z",
    "data": {
      "code": "AAAAAAAA",
      "id": "f9810606-691e-418d-aef6-d23e3f004796",
      "resource": "charge",
      "name": "The Sovereign Individual",
      "description": "Mastering the Transition to the Information Age",
      "hosted_url": "https://commerce.coinbase.com/charges/AAAAAAAA",
      "created_at": "2018-01-01T00:00:00Z",
      "confirmed_at": "2018-01-01T00:40:00Z",
      "expires_at": "2018-01-01T01:00:00Z",
      "support_email": "test@test.test",
      "timeline": [
        {
          "time": "2018-01-01T00:00:00Z",
          "status": "NEW"
        },
        {
          "status": "PENDING",
          "payment": {
            "network": "ethereum",
            "transaction_id": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          "time": "2018-01-01T00:30:00Z"
        },
        {
          "status": "COMPLETED",
          "payment": {
            "network": "ethereum",
            "transaction_id": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          "time": "2018-01-01T00:40:00Z"
        }
      ],
      "metadata": {},
      "pricing": {
        "local": {
          "amount": "100.00",
          "currency": "USD"
        },
        "bitcoin": {
          "amount": "1.00000000",
          "currency": "BTC"
        },
        "ethereum": {
          "amount": "10.000000000",
          "currency": "ETH"
        },
        "usdc": {
          "amount": "10.000000",
          "currency": "USDC"
        }
      },
      "pricing_type": "fixed_price",
      "payments": [
        {
          "network": "ethereum",
          "transaction_id": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "status": "CONFIRMED",
          "detected_at": "2018-01-01T00:30:00Z",
          "value": {
            "local": {
              "amount": "100.0",
              "currency": "USD"
            },
            "crypto": {
              "amount": "10.00",
              "currency": "ETH"
            }
          },
          "block": {
            "height": 100,
            "hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "confirmations_accumulated": 8,
            "confirmations_required": 2
          }
        }
      ],
      "addresses": {
        "bitcoin": "1000000000000000000000000000000000",
        "ethereum": "0x0000000000000000000000000000000000000000",
        "usdc": "0x0000000000000000000000000000000000000000"
      }
    },
    "id": "677035f9-3b27-42c5-a98d-3629bf0c7465",
    "resource": "event",
    "type": "charge:failed"
  },
  "id": "7fe8e4e8-95ca-43b2-8c57-b0ae35efee8a",
  "scheduled_for": "2020-06-01T19:43:19Z"
}

###
POST http://localhost:4003/webhook/stripe?key=STRIPE
Content-Type: application/json

{
  "object": {
    "id": "in_1LUEvhJslj2vUcp7gOg9oUtz",
    "object": "invoice",
    "account_country": "US",
    "account_name": "Open Template Hub",
    "account_tax_ids": null,
    "amount_due": 100,
    "amount_paid": 100,
    "amount_remaining": 0,
    "application": null,
    "application_fee_amount": null,
    "attempt_count": 1,
    "attempted": true,
    "auto_advance": false,
    "automatic_tax": {
      "enabled": false,
      "status": null
    },
    "billing_reason": "subscription_create",
    "charge": "ch_3LUEvhJslj2vUcp71Sud9VFc",
    "collection_method": "charge_automatically",
    "created": 1659899669,
    "currency": "usd",
    "custom_fields": null,
    "customer": "cus_MCeDP6lt8GmZ3X",
    "customer_address": null,
    "customer_email": "mertsarac@yandex.com",
    "customer_name": "mert",
    "customer_phone": null,
    "customer_shipping": null,
    "customer_tax_exempt": "none",
    "customer_tax_ids": [
    ],
    "default_payment_method": null,
    "default_source": null,
    "default_tax_rates": [
    ],
    "description": null,
    "discount": null,
    "discounts": [
    ],
    "due_date": null,
    "ending_balance": 0,
    "footer": null,
    "hosted_invoice_url": "https://invoice.stripe.com/i/acct_1I4pFdJslj2vUcp7/test_YWNjdF8xSTRwRmRKc2xqMnZVY3A3LF9NQ2VFeGRGVjRJMkdySkVkMXdVRmFMQ2ZYOXZtd29HLDUwNDQwNDcz0200BTuGpKbM?s=ap",
    "invoice_pdf": "https://pay.stripe.com/invoice/acct_1I4pFdJslj2vUcp7/test_YWNjdF8xSTRwRmRKc2xqMnZVY3A3LF9NQ2VFeGRGVjRJMkdySkVkMXdVRmFMQ2ZYOXZtd29HLDUwNDQwNDcz0200BTuGpKbM/pdf?s=ap",
    "last_finalization_error": null,
    "lines": {
      "object": "list",
      "data": [
        {
          "id": "il_1LUEvhJslj2vUcp71Fa5FrLo",
          "object": "line_item",
          "amount": 100,
          "amount_excluding_tax": 100,
          "currency": "usd",
          "description": "1 × Starter (at $1.00 / day)",
          "discount_amounts": [
          ],
          "discountable": true,
          "discounts": [
          ],
          "livemode": false,
          "metadata": {
          },
          "period": {
            "end": 1659986069,
            "start": 1659899669
          },
          "plan": {
            "id": "price_1LTOdcJslj2vUcp7MYqbEskb",
            "object": "plan",
            "active": true,
            "aggregate_usage": null,
            "amount": 100,
            "amount_decimal": "100",
            "billing_scheme": "per_unit",
            "created": 1659698660,
            "currency": "usd",
            "interval": "day",
            "interval_count": 1,
            "livemode": false,
            "metadata": {
            },
            "nickname": null,
            "product": "prod_LzZFaItMLfg5dr",
            "tiers_mode": null,
            "transform_usage": null,
            "trial_period_days": null,
            "usage_type": "licensed"
          },
          "price": {
            "id": "price_1LTOdcJslj2vUcp7MYqbEskb",
            "object": "price",
            "active": true,
            "billing_scheme": "per_unit",
            "created": 1659698660,
            "currency": "usd",
            "custom_unit_amount": null,
            "livemode": false,
            "lookup_key": null,
            "metadata": {
            },
            "nickname": null,
            "product": "prod_LzZFaItMLfg5dr",
            "recurring": {
              "aggregate_usage": null,
              "interval": "day",
              "interval_count": 1,
              "trial_period_days": null,
              "usage_type": "licensed"
            },
            "tax_behavior": "unspecified",
            "tiers_mode": null,
            "transform_quantity": null,
            "type": "recurring",
            "unit_amount": 100,
            "unit_amount_decimal": "100"
          },
          "proration": false,
          "proration_details": {
            "credited_items": null
          },
          "quantity": 1,
          "subscription": "sub_1LUEvhJslj2vUcp7yFGkKFWv",
          "subscription_item": "si_MCeEyNpfJKVBnP",
          "tax_amounts": [
          ],
          "tax_rates": [
          ],
          "type": "subscription",
          "unit_amount_excluding_tax": "100"
        }
      ],
      "has_more": false,
      "total_count": 1,
      "url": "/v1/invoices/in_1LUEvhJslj2vUcp7gOg9oUtz/lines"
    },
    "livemode": false,
    "metadata": {
    },
    "next_payment_attempt": null,
    "number": "64A1573A-0001",
    "on_behalf_of": null,
    "paid": true,
    "paid_out_of_band": false,
    "payment_intent": "pi_3LUEvhJslj2vUcp71VXL3mqY",
    "payment_settings": {
      "default_mandate": null,
      "payment_method_options": null,
      "payment_method_types": null
    },
    "period_end": 1659899669,
    "period_start": 1659899669,
    "post_payment_credit_notes_amount": 0,
    "pre_payment_credit_notes_amount": 0,
    "quote": null,
    "receipt_number": null,
    "rendering_options": null,
    "starting_balance": 0,
    "statement_descriptor": null,
    "status": "paid",
    "status_transitions": {
      "finalized_at": 1659899669,
      "marked_uncollectible_at": null,
      "paid_at": 1659899671,
      "voided_at": null
    },
    "subscription": "sub_1LUEvhJslj2vUcp7yFGkKFWv",
    "subtotal": 100,
    "subtotal_excluding_tax": 100,
    "tax": null,
    "test_clock": null,
    "total": 100,
    "total_discount_amounts": [
    ],
    "total_excluding_tax": 100,
    "total_tax_amounts": [
    ],
    "transfer_data": null,
    "webhooks_delivered_at": 1659899669
  }
}

###
POST http://localhost:4003/webhook/paypal?key=PAYPAL
Content-Type: application/json

{
  "id": "WH-7EJ96441K1110272N-59895742AK7079143",
  "event_version": "1.0",
  "create_time": "2020-06-03T12:37:03.696Z",
  "resource_type": "checkout-order",
  "resource_version": "2.0",
  "event_type": "CHECKOUT.ORDER.APPROVED",
  "summary": "An order has been approved by buyer",
  "resource": {
    "create_time": "2020-06-03T12:36:28Z",
    "purchase_units": [
      {
        "reference_id": "default",
        "amount": {
          "currency_code": "USD",
          "value": "2.00"
        },
        "payee": {
          "email_address": "sb-nlx1y1717487@business.example.com",
          "merchant_id": "MFZ2X4BDN42NG"
        },
        "shipping": {
          "name": {
            "full_name": "Furkan Yavuz"
          },
          "address": {
            "address_line_1": "PO Box 4668 New York, NY 10163 NEW YORK, NY 10163",
            "admin_area_2": "New York",
            "admin_area_1": "NY",
            "postal_code": "10163",
            "country_code": "US"
          }
        }
      }
    ],
    "links": [
      {
        "href": "https://api.sandbox.paypal.com/v2/checkout/orders/2P1869875K633350G",
        "rel": "self",
        "method": "GET"
      },
      {
        "href": "https://api.sandbox.paypal.com/v2/checkout/orders/2P1869875K633350G",
        "rel": "update",
        "method": "PATCH"
      },
      {
        "href": "https://api.sandbox.paypal.com/v2/checkout/orders/2P1869875K633350G/capture",
        "rel": "capture",
        "method": "POST"
      }
    ],
    "id": "7FL70342K0370561L",
    "intent": "CAPTURE",
    "payer": {
      "name": {
        "given_name": "Furkan",
        "surname": "Yavuz"
      },
      "email_address": "furkanyavuz.spambox@gmail.com",
      "payer_id": "D2P2HDVA2Z6H8",
      "address": {
        "country_code": "US"
      }
    },
    "status": "APPROVED"
  },
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-7EJ96441K1110272N-59895742AK7079143",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-7EJ96441K1110272N-59895742AK7079143/resend",
      "rel": "resend",
      "method": "POST"
    }
  ]
}
