name: On Push to Master Workflows

on:
  push:
    branches:
      - "master"

jobs:
  continuous-integration:
    name: "Npm Continuous Integration"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: NPM Install
        run: npm install
      - name: NPM Continous Integration
        run: npm ci

  bump-version:
    name: "Update Version"
    needs: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bump Version and Create Tag
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
